# -*- coding: utf-8 -*-
"""ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rYScDe1SxuqUQFNTJ0pS9O3MQ4lYane

**Simple** **Linear** **Regression**

For a given student record consisting of no. of "Hours" and "Marks scored". Find approx marks required for a student to pass in the exam. How much a student score if he or she study for 10 hours?
Model = LinearRegression()
Output = Marks scored

Data Collection: 1. Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""DATA COLLECTION / DATA PREPROCESSING"""

X = np.array([1,2,3,4,5,6]).reshape(-1, 1)
Y = np.array([10, 20, 30, 35, 40, 45])

"""  MODEL SELECTION"""

from sklearn import linear_model
model = linear_model.LinearRegression()

"""MODEL FIT"""

model.fit(X, Y)

"""MODEL TRAINING"""

hours = 10
marks = model.predict([[hours]])
print(marks)

[74.37142857]